version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html
    networks:
      - symfony
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    entrypoint: /var/www/html/entrypoint.sh
    command: ["sh", "-c", "chmod +x /var/www/html/entrypoint.sh && /var/www/html/entrypoint.sh"]

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  dbdata:
